- README.md
Now that TrackAudio is in the Archlinux AUR, reference it in the README file
> README: Add Archlinux install instructions

- README.md
Fixes #14 
* Added the Windows requirements
* Added a note about the `cmake-js` requirement
* Reordered the initial build steps
* Separated initial build steps from ongoing build steps
> Update readme with build steps, including new steps for Windows

- src/app/components/bootstrap.tsx
- src/app/components/sidebar/add-frequency.tsx
- src/app/helpers/CallsignHelper.ts
- src/app/helpers/RadioHelper.ts
- src/app/store/radioStore.ts
Fixes #12
Draft pull request with the initial work for feedback. Summary of changes:
1. Add a new `RadioHelper.ts` file that includes a `radioCompare` method to compare two radios for sorting
2. Add a new `getCallsignParts` method that takes a callsign and splits it out into the station, position, and subposition
3. Add new `station`, `position`, and `subPosition` properties on a radio and set them when radios are added. These are used for sorting later
4.  Pass the connected station callsign through when adding radios
The sorting winds up being a bit of a pain to make things look right in the list. Here's the logic:
1. The connected station always goes to the front of the list
2. Remaining stations are sorted by station name, then by position, then by sub-position (if any)
In my playing …
> Make the sort order of stations consistent

- src/app/helpers/CallsignHelper.ts
Fixes #21
Change the order of the empty sub-position string in the return from `getCallsignParts`.
After the fix:
> Stations without a subposition don't sort properly

- src/app/components/mini.tsx
Fixes #20
Show an empty string (to match how "Last RX" is displayed in the larger view) for radios that haven't received a transmission yet.
I have no idea why I suggested the more complicated way to fix this. This way is so simple.
With this change, before any transmissions:
With this change, after a transmission:
> Show empty received radios in mini view

- .vscode/launch.json
Fixes #26
Adds a launch.json to enable debugging both the main and the rendering process.
Here is a breakpoint getting hit in the main process:
And here's one getting hit in the rendering process:
> Add vscode debug configuration

- src/app/components/mini.tsx
Fixes #24
Highlights the station name on Tx:
And the callsign on Rx:
> Show active receive in the mini view

- README.md
I created a Homebrew tap for macOS users, which let's them install TrackAudio easily by using a terminal command. The advantage of this is, that TrackAudio is easily patched using `brew upgrade`. I already did this for VectorAudio two years ago and would love to support the Homebrew tap again, this time for TrackAudio.
This PR adds the instructions in the README for installing TrackAudio using homebrew. The homebrew cask respects the architecture and selects the release correctly depending on the system you are using.
> Edit README to include newly created Homebrew tap

- src/app/components/navbar.tsx
Fixes #60
* Adds an `onWheel` event handler to the gain label and slider, capping the gain between 0 and 100 in 1 step
* Refactors the code to set the gain out to its own method
* Use that refactored method in both the `onWheel` and `onSlider` event handlers
* Updates the slider to use `value` instead of `defaultValue` so it updates automatically when the gain value changes
In action:
> Add scroll wheel support for setting gain

- src/app/style/app.scss
- src/index.ts
Fixes #79
* Use `getContentSize()` and a fixed 300-pixel width as the test for whether to restore from mini-mode
I'm not wild about the hardcoded `300` value but making it a .scss variable and then reading that at runtime would require far more extensive changes that don't seem worth it.
> Fix restoring from mini mode on Windows

- src/index.ts
Fixes #85
* Add a new `isInMiniMode()` method to reduce code duplication
* Use the new method as the test before saving the window position on close
> Don't save window position on close when in mini mode

- src/index.ts
Fixes #84
* Add a test for the window being maximized, and un-maximize before setting the window to mini-mode
> Enable switching to mini-mode when window is maximized

- src/main/index.ts
Fixes #90
I have no idea if this actually fixes the problem, but it might.
> Make 'always on top' always work on Windows

- package.json
Fixes #100 
Stops vscode complaining about being unable to find type information for things like `<>` when editing the React code.
> Add @types/react to package.json

- backend/src/main.cpp
Fixes #108
* Use the std path concat operator to join the filename instead of a string concat
> Ensure log files get written to the correct folder

- src/renderer/index.html
Fixes #110 
* Remove the preload flag from the link
> Fix font preload warning

- src/main/config.d.ts
- src/main/index.ts
- src/preload/bindings.ts
- src/renderer/src/components/settings-modal/settings-modal.tsx
Fixes #113
* Change the always on top setting from a boolean to a list of valid options: `always`, `never` and `inMiniMode`
* Use the setting to determine whether always on top should be set when entering/leaving mini mode
* Handle upgrading prior versions that used a boolean value
* Fix a few places where the always on top fix for Windows wasn't properly applied
New dropdown in settings looks like this:
> Add an "in mini mode" option for always on top

- electron.vite.config.ts
For some reason, this breaks the Mac x64 application. We also don't particularly need it, as the performance benefit is minimal, and our application is open-source and doesn't need source protection.
Tested live at FSExpo (thanks Colton!) on an Intel Mac.
> Remove bytecode compilation

- src/renderer/src/components/settings-modal/settings-modal.tsx
Fixes #127
* Change the input field type to text instead of `number`
* Make the input field controlled
* Strip any non-digit characters from the input
I have no idea if this is actually the fix for the problem since I can't reproduce it. However, this was the only place in the code that attempted to treat the value as a number, so it's possible the browser happened to try and display it in scientific notation for some reason.
Tested on Windows that I can still type digits in, use the backspace key, and paste in a CID without issue. Any non-digit characters simply don't appear.
> Ensure CID always shows as a number

- src/main/index.ts
- src/renderer/src/components/settings-modal/settings-modal.tsx
I'm lucky, on Windows my `audioApi` value is `0`. This exposed a host of problems in the code that tested the value of `audioApi` using logical or. This resulted in a default value of `-1` being used when calling afv-native, and basically broke all audio.
Changes:
* Create a new `defaultConfiguration` object that defines the default value for all configuration properties
* When reading a saved configuration from storage first apply the default configuration, then apply the saved values. This ensure the `currentConfiguration` object always has a value for all the properties, even if it's first run of the app or one of the properties was manually deleted from the saved config.
* Remove places in the code that used `||` as a method of catching undefined/invalid configuration values since …
> Fix audio issues on Windows, properly handle default config values

- eslint.config.mjs
- src/main/index.ts
- src/preload/bindings.ts
- src/renderer/src/app.tsx
- src/renderer/src/components/error.tsx
- src/renderer/src/components/sidebar/lastReceivedCallsigns.tsx
- tsconfig.node.json
- tsconfig.web.json
Fixes #134
Enables the following rules and `strictNullChecks`:
* recommendedTypeChecked
* stylisticTypeChecked
* strictTypeChecked
Also fixes all errors thrown by the new rules. Most of the reported errors were around missing handling of async operations, easily resolved with a `.catch()`. There was also one instance of an await being used on a non-async method, and some whitespace cleanup.
> Add additional linting, fix reported errors

- backend/include/RadioHelper.hpp
- backend/src/sdk.cpp
> Properly enforce 'rx' and 'tx' rules when processing websocket message

- backend/include/sdk.hpp
- backend/include/sdkWebsocketMessage.hpp
- backend/src/main.cpp
- backend/src/sdk.cpp
Fixes #140 
* Adds the two events
* Calls `kFrequencyRemoved` when a frequency is removed in TrackAudio
* Replaces `kStationStateUpdated` with `kStationAdded` when `StationDataReceived` or `VccsReceived` events happen
> Add `kStationAdded` and `kFrequencyRemoved` websocket events

- .github/workflows/ci.yml
Fixes #168 
Adds the artifacts to the end of the action run. [See the run for this PR as an example](https://github.com/pierr3/TrackAudio/actions/runs/10761575125):
Note that the mac binaries are not signed, which is expected.
> Attach CI artifacts to the run result

- backend/src/main.cpp
- backend/types/index.d.ts
- package-lock.json
- src/main/config.ts
- src/main/index.ts
- src/preload/bindings.ts
- src/renderer/src/components/settings-modal/settings-modal.tsx
This pull requests add the hardwareTypeIndex to the "No_Hardware" type of the HardwareType enum and the "No Hardware (Real Radio Affects disabled)" option with value 3 to the hardware select of the settings-modal.tsx, to make it possible to disable radio affects in TrackAudio.
This pull request shall implement the issue: https://github.com/pierr3/TrackAudio/issues/156
This pull request is dependent on the afv-native pull request: https://github.com/pierr3/afv-native/pull/13
> Add No_Hardware as HardwareType to disable radio audio effects

- src/renderer/src/helpers/RadioHelper.ts
Fixes #198
Forces GUARD and UNICOM to be at the bottom of the mini-mode list so they don't break up the actual frequencies you may be staffing/listening to.
While it's not *explicitly* making GUARD show before UNICOM, in my testing that's how they've always wound up sorting with this code so I'm calling it good enough...
> Sort GUARD and UNICOM to the bottom of the mini-mode list

- backend/include/sdk.hpp
- backend/src/main.cpp
- backend/src/sdk.cpp
Fixes #261 
Example message now for a station with an alias, new property included:
```json
{
"type": "kStationAdded",
"value": {
"callsign": "NAT_FSS",
"frequency": 5649000,
"frequencyAlias": 131900000
}
}
```
Example message now for a station without an alias, unchanged from current behaviour:
```json
{
"type": "kStationAdded",
"value": {
"callsign": "CZQO_DEL",
"frequency": 128700000
}
}
```
> Add `frequencyAlias` to `kStationAdded` messages
